apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: vault-cluster-backend
spec:
  provider:
    vault:
      auth:
        kubernetes:
          mountPath: kubernetes
          role: backstage
          serviceAccountRef:
            name: backstage
            namespace: backstage
      path: secret
      server: http://vault.vault.svc.cluster.local:8200
      version: v2
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: supabase-vault-secrets
  namespace: supabase
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-cluster-backend
    kind: ClusterSecretStore
  target:
    name: supabase-vault-credentials
    creationPolicy: Owner
  data:
    - secretKey: anonKey
      remoteRef:
        key: supabase/credentials
        property: anon_key
    - secretKey: serviceKey
      remoteRef:
        key: supabase/credentials
        property: service_key
    - secretKey: secret
      remoteRef:
        key: supabase/credentials
        property: jwt_secret
    - secretKey: postgres-password
      remoteRef:
        key: supabase/credentials
        property: postgres_password
    - secretKey: meta-crypto-key
      remoteRef:
        key: supabase/credentials
        property: meta_crypto_key
